--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Blugin/libCommand
branches:
  - master
projects:
  libcommand:
    model: virion
    type: library
    lint:
      phpstan: false
...
